name: IC Zenith Magazine
favicon: null
layout_spectrum: 0.574906415771693
typography_spectrum: 0.6925706332549453
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#670237'
    - '#ceadbe'
    - '#000000'
    - '#3a568f'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
