name: Irresistible Communications
favicon: null
layout_spectrum: 0.0041
typography_spectrum: 0.14344
title: IC Zenith Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfafa'
    - '#690237'
    - '#9b577a'
    - '#d7becb'
    - '#c29daf'
  brandStrength: 0
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0
purpose: []
