name: IC Zenith Magazine
favicon: null
layout_spectrum: 0.574906415771693
typography_spectrum: 0.6925706332549453
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1216619098559022
  lightness: 0.6901411646977067
  saturation: 0.2535396779421717
  rhythmicContrast: 0.24165541166439652
purpose: []
