name: Irresistible Communications
favicon: null
layout_spectrum: 0.01066
typography_spectrum: 0.14344
title: IC Zenith Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#670237'
    - '#85355f'
    - '#c39bb0'
    - '#132433'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
