name: Irresistible Communications
favicon: null
layout_spectrum: 0.01066
typography_spectrum: 0.55164
title: IC Zenith Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c0b1b6'
    - '#825861'
    - '#370e13'
    - '#988523'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
