name: Irresistible Communications
favicon: null
layout_spectrum: 0.01066
typography_spectrum: 0.55164
title: IC Zenith Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#781236'
    - '#f0f1fa'
    - '#010003'
    - '#2c447b'
    - '#a0b0ce'
  brandStrength: 0.4375
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
